version: "3.7"
services:
  db:
    image: "mysql"
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    expose:
      - 3306
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
volumes:
  data:
